import type { DocsArticle } from './types';

/**
 * Every article describes the app as it is in production. Before publishing a
 * change here, check the screen it describes; if a control was renamed, the
 * `{ui:…}` markers follow automatically, the prose does not.
 */
export const ARTICLES: DocsArticle[] = [
	// ------------------------------------------------------------------ start
	{
		slug: 'rychly-start',
		category: 'start',
		audiences: ['ALL'],
		order: 1,
		updatedAt: '2026-09-14',
		published: true,
		related: ['role-a-opravneni', 'ucet-a-prihlaseni', 'sprava-sezony'],
		content: {
			cs: {
				title: 'Rychlý start',
				summary: 'Základní orientace v ATM pro návštěvníky i nové manažery.',
				keywords: ['začátek', 'orientace', 'navigace', 'nástěnka', 'menu'],
				blocks: [
					{ type: 'h', id: 'co-je-atm', text: 'Co je ATM' },
					{ type: 'p', text: 'ATM slouží ke správě amatérských lig, turnajů, týmů, hráčů a zápasů. Ve veřejné části můžete bez přihlášení sledovat soutěže, rozpisy, výsledky, tabulky a statistiky hráčů. Po přihlášení spravujete to, co vám bylo svěřeno – ligu, tým nebo sérii turnajů.' },
					{ type: 'h', id: 'verejna-cast', text: 'Veřejná část' },
					{ type: 'defs', items: [
						['{ui:public.nav.competitions}', '{ui:public.nav.leagues}, {ui:public.nav.seasons} a {ui:public.nav.tournaments}.'],
						['{ui:public.nav.teams}', 'Profily týmů, soupisky a odehrané zápasy.'],
						['{ui:public.nav.players}', 'Hráči a jejich statistiky.'],
						['{ui:public.nav.games}', 'Nadcházející, právě hrané a odehrané zápasy.'],
						['{ui:public.nav.stats}', 'Pořadí hráčů napříč soutěžemi.'],
					] },
					{ type: 'h', id: 'po-prihlaseni', text: 'První kroky po přihlášení' },
					{ type: 'steps', items: [
						'Po přihlášení se otevře {ui:public.nav.dashboard}.',
						'Otevřete menu účtu. Štítky {ui:hats.leagueManager}, {ui:hats.teamManager} a {ui:hats.tournamentManager} ukazují, co spravujete.',
						'Zvolte oblast: {ui:nav.myTeams}, {ui:nav.mySeasons} nebo {ui:nav.manageTournaments}. V menu jsou jen oblasti, které spravujete.',
						'Před každou změnou zkontrolujte název týmu nebo sezóny v záhlaví.',
					] },
					{ type: 'note', tone: 'tip', text: 'Pokud spravujete ligu i tým, máte obě oblasti v menu současně. Přepínáním mezi nimi se vaše oprávnění nemění.' },
				],
			},
			en: {
				title: 'Quick start',
				summary: 'Finding your way around ATM, for visitors and new managers.',
				keywords: ['start', 'overview', 'navigation', 'dashboard', 'menu'],
				blocks: [
					{ type: 'h', id: 'co-je-atm', text: 'What ATM is' },
					{ type: 'p', text: 'ATM runs amateur leagues, tournaments, teams, players and games. The public part shows competitions, schedules, results, tables and player statistics without signing in. Once signed in, you manage what you have been given – a league, a team or a tournament series.' },
					{ type: 'h', id: 'verejna-cast', text: 'The public part' },
					{ type: 'defs', items: [
						['{ui:public.nav.competitions}', '{ui:public.nav.leagues}, {ui:public.nav.seasons} and {ui:public.nav.tournaments}.'],
						['{ui:public.nav.teams}', 'Team profiles, rosters and played games.'],
						['{ui:public.nav.players}', 'Players and their statistics.'],
						['{ui:public.nav.games}', 'Upcoming, live and played games.'],
						['{ui:public.nav.stats}', 'Player rankings across competitions.'],
					] },
					{ type: 'h', id: 'po-prihlaseni', text: 'After signing in' },
					{ type: 'steps', items: [
						'Signing in opens the {ui:public.nav.dashboard}.',
						'Open the account menu. The {ui:hats.leagueManager}, {ui:hats.teamManager} and {ui:hats.tournamentManager} badges show what you manage.',
						'Pick an area: {ui:nav.myTeams}, {ui:nav.mySeasons} or {ui:nav.manageTournaments}. The menu lists only the areas you manage.',
						'Before any change, check the team or season name in the header.',
					] },
					{ type: 'note', tone: 'tip', text: 'If you manage a league and a team, both areas are in the menu at once. Moving between them does not change what you are allowed to do.' },
				],
			},
		},
	},
	{
		slug: 'role-a-opravneni',
		category: 'start',
		audiences: ['ALL'],
		order: 2,
		updatedAt: '2026-09-14',
		published: true,
		related: ['sprava-sezony', 'sprava-tymu', 'ucet-a-prihlaseni'],
		content: {
			cs: {
				title: 'Role a oprávnění',
				summary: 'Kdo v ATM co smí a jak se oprávnění získávají.',
				keywords: ['role', 'oprávnění', 'přístup', 'manažer', 'pozvánka', 'administrátor'],
				blocks: [
					{ type: 'h', id: 'jak-to-funguje', text: 'Oprávnění plynou z toho, co spravujete' },
					{ type: 'p', text: 'Na účtu se nevybírá role. Manažerem se stanete tím, že ligu, tým nebo sérii turnajů spravujete. Jeden účet tak může řídit ligu a zároveň vést tým, který v ní hraje.' },
					{ type: 'h', id: 'navstevnik', text: 'Veřejný návštěvník' },
					{ type: 'p', text: 'Bez přihlášení lze procházet zveřejněné soutěže, týmy, hráče, zápasy, tabulky a statistiky. Neveřejnou sezónu otevře jen ten, kdo má odkaz; skrytou nevidí nikdo kromě jejích správců.' },
					{ type: 'h', id: 'manazer-ligy', text: 'Manažer ligy' },
					{ type: 'list', items: [
						'zakládá sezóny a mění jejich stav, viditelnost a bodování;',
						'přidává a odebírá týmy v sezóně a dělí ji do skupin;',
						'zve manažery týmů;',
						'generuje rozpis, nastavuje termíny a zapisuje výsledky a zápisy o utkání;',
						'potvrzuje zápisy a znovu je otevírá;',
						'spravuje také každý tým, který hraje v jeho sezóně.',
					] },
					{ type: 'h', id: 'manazer-tymu', text: 'Manažer týmu' },
					{ type: 'list', items: [
						'upravuje název, logo a barvu týmu;',
						'spravuje soupisku a propojuje hráče s jejich účty;',
						'plánuje události v kalendáři a sleduje docházku;',
						'u zápasu bez zápisu o utkání vyplňuje góly, asistence a trestné minuty svých hráčů.',
					] },
					{ type: 'p', text: 'Termín ani skóre zápasu manažer týmu nemění, rozpis negeneruje, zápisy nepotvrzuje a tým neodebírá ani nemaže.' },
					{ type: 'h', id: 'manazer-turnaje', text: 'Manažer turnaje' },
					{ type: 'p', text: 'Spravuje sérii turnajů a vše v ní: účastníky, skupiny, rozpis, výsledky a playoff.' },
					{ type: 'h', id: 'ziskani', text: 'Jak se oprávnění získávají' },
					{ type: 'list', items: [
						'Manažera týmu zve manažer ligy nebo administrátor tlačítkem {ui:teamDetail.inviteManager.button}.',
						'Manažera ligy určuje administrátor.',
						'Hráč s propojeným účtem vidí svůj tým a odpovídá na docházku; tým spravovat nemůže.',
					] },
					{ type: 'note', tone: 'important', text: 'Když očekávaný tým nebo ligu nevidíte, nezakládejte nový záznam. Požádejte manažera ligy o novou pozvánku.' },
				],
			},
			en: {
				title: 'Roles and permissions',
				summary: 'Who can do what in ATM, and how access is given.',
				keywords: ['role', 'permissions', 'access', 'manager', 'invitation', 'administrator'],
				blocks: [
					{ type: 'h', id: 'jak-to-funguje', text: 'Access follows what you manage' },
					{ type: 'p', text: 'There is no role to pick on your account. You become a manager by managing a league, a team or a tournament series. One account can run a league and coach a team playing in it.' },
					{ type: 'h', id: 'navstevnik', text: 'Visitors' },
					{ type: 'p', text: 'Without signing in you can browse published competitions, teams, players, games, tables and statistics. An unpublished season opens only from its link; a hidden one is seen only by the people who manage it.' },
					{ type: 'h', id: 'manazer-ligy', text: 'League manager' },
					{ type: 'list', items: [
						'creates seasons and sets their status, visibility and scoring;',
						'adds and removes teams in a season and splits it into divisions;',
						'invites team managers;',
						'generates the schedule, sets dates, records results and match reports;',
						'confirms match reports and reopens them;',
						'can also manage every team playing in their season.',
					] },
					{ type: 'h', id: 'manazer-tymu', text: 'Team manager' },
					{ type: 'list', items: [
						'edits the team name, logo and colour;',
						'keeps the roster and links players to their accounts;',
						'plans calendar events and follows attendance;',
						'for a game without a match report, fills in goals, assists and penalty minutes for their own players.',
					] },
					{ type: 'p', text: 'A team manager does not change dates or scores, generate the schedule, confirm reports, or remove or delete the team.' },
					{ type: 'h', id: 'manazer-turnaje', text: 'Tournament manager' },
					{ type: 'p', text: 'Runs a tournament series and everything in it: entrants, groups, schedule, results and playoff.' },
					{ type: 'h', id: 'ziskani', text: 'How access is given' },
					{ type: 'list', items: [
						'A team manager is invited by the league manager or an administrator with {ui:teamDetail.inviteManager.button}.',
						'A league manager is appointed by an administrator.',
						'A player linked to an account sees their team and answers attendance, but cannot manage the team.',
					] },
					{ type: 'note', tone: 'important', text: 'If a team or league you expect is missing, do not create a new one. Ask the league manager for a new invitation.' },
				],
			},
		},
	},
	{
		slug: 'ucet-a-prihlaseni',
		category: 'start',
		audiences: ['ALL'],
		order: 3,
		updatedAt: '2026-09-14',
		published: true,
		related: ['role-a-opravneni', 'rychly-start'],
		content: {
			cs: {
				title: 'Účet a přihlášení',
				summary: 'Registrace, aktivace účtu, přihlášení a obnova hesla.',
				keywords: ['účet', 'registrace', 'aktivace', 'přihlášení', 'heslo', 'e-mail', 'pozvánka'],
				blocks: [
					{ type: 'h', id: 'aktivace', text: 'Registrace a aktivace' },
					{ type: 'p', text: 'Po registraci vám přijde e-mail s aktivačním odkazem. Dokud účet neaktivujete, přihlásit se nelze. E-mail hledejte i ve složce s nevyžádanou poštou.' },
					{ type: 'p', text: 'Pozvánka manažera týmu na e-mail, se kterým už účet máte, připojí tým k tomuto účtu.' },
					{ type: 'h', id: 'prihlaseni', text: 'Přihlášení' },
					{ type: 'steps', items: [
						'V hlavičce zvolte {ui:public.nav.signIn}.',
						'Zadejte e-mail a heslo.',
						'Otevře se {ui:public.nav.dashboard}; spravované oblasti najdete v menu účtu.',
					] },
					{ type: 'h', id: 'heslo', text: 'Zapomenuté heslo' },
					{ type: 'p', text: 'Na přihlašovací stránce zvolte {ui:auth.login.forgotPassword}, zadejte e-mail a zvolte {ui:auth.forgotPassword.submit}. Pokud účet existuje, přijde vám odkaz pro nastavení nového hesla.' },
					{ type: 'h', id: 'deaktivace', text: 'Deaktivovaný účet' },
					{ type: 'p', text: 'Deaktivovaný účet se přihlásit nemůže. Obnovit ho může administrátor.' },
					{ type: 'note', tone: 'tip', text: 'Každý manažer by měl mít vlastní účet. Po práci na sdíleném zařízení se odhlaste.' },
				],
			},
			en: {
				title: 'Account and signing in',
				summary: 'Registering, activating your account, signing in and resetting a password.',
				keywords: ['account', 'register', 'activation', 'sign in', 'password', 'email', 'invitation'],
				blocks: [
					{ type: 'h', id: 'aktivace', text: 'Registering and activating' },
					{ type: 'p', text: 'After registering you receive an email with an activation link. You cannot sign in until the account is activated. Check your spam folder too.' },
					{ type: 'p', text: 'A team manager invitation sent to an email you already use joins the team to that account.' },
					{ type: 'h', id: 'prihlaseni', text: 'Signing in' },
					{ type: 'steps', items: [
						'Choose {ui:public.nav.signIn} in the header.',
						'Enter your email and password.',
						'The {ui:public.nav.dashboard} opens; the areas you manage are in the account menu.',
					] },
					{ type: 'h', id: 'heslo', text: 'Forgotten password' },
					{ type: 'p', text: 'On the sign-in page choose {ui:auth.login.forgotPassword}, enter your email and choose {ui:auth.forgotPassword.submit}. If the account exists, you receive a link to set a new password.' },
					{ type: 'h', id: 'deaktivace', text: 'Deactivated account' },
					{ type: 'p', text: 'A deactivated account cannot sign in. An administrator can restore it.' },
					{ type: 'note', tone: 'tip', text: 'Every manager should have their own account. Sign out after using a shared device.' },
				],
			},
		},
	},

	// ----------------------------------------------------------------- league
	{
		slug: 'sprava-sezony',
		category: 'league',
		audiences: ['LEAGUE'],
		order: 1,
		updatedAt: '2026-09-14',
		published: true,
		related: ['sezony-a-tymy', 'rozpis-zapasu', 'vysledky-a-statistiky'],
		content: {
			cs: {
				title: 'Správa sezóny',
				summary: 'Kde správu sezóny najdete a co kontrolovat pravidelně.',
				keywords: ['sezóna', 'přehled', 'záložky', 'pozornost', 'viditelnost', 'bodování'],
				blocks: [
					{ type: 'h', id: 'kde', text: 'Kde správu najdete' },
					{ type: 'p', text: 'V menu účtu zvolte {ui:nav.mySeasons} a otevřete sezónu. Správa má záložky {ui:seasonManagement.tabs.season}, {ui:seasonManagement.tabs.games}, {ui:seasonManagement.tabs.teams}, {ui:seasonManagement.tabs.table} a {ui:seasonManagement.tabs.more}.' },
					{ type: 'h', id: 'zalozka-sezona', text: 'Záložka Sezóna' },
					{ type: 'list', items: [
						'stav sezóny s akcí {ui:seasonManagement.publish.action} nebo {ui:seasonManagement.publish.complete};',
						'počty týmů, zápasů a odehraných zápasů;',
						'{ui:seasonManagement.attention.label} – sezóna bez týmů, bez rozpisu nebo zápasy bez termínu;',
						'{ui:seasonManagement.nextUp.label}.',
					] },
					{ type: 'h', id: 'kontrola', text: 'Co kontrolovat pravidelně' },
					{ type: 'steps', items: [
						'Mají všechny zápasy termín? Zápasy bez termínu týmy ve svém rozpisu nevidí.',
						'Čekají odehrané zápasy na potvrzení? V tabulce jsou označené {ui:seasonManagement.table.awaitingConfirmation} a do pořadí se zatím nepočítají.',
						'Má sezóna správnou viditelnost?',
					] },
					{ type: 'h', id: 'vice', text: 'Záložka Více' },
					{ type: 'list', items: [
						'{ui:seasonManagement.more.generateSchedule}',
						'{ui:seasonManagement.more.scoring} – body za výhru a remízu; bez úpravy platí výchozí nastavení sportu.',
						'{ui:seasonManagement.more.divisions} – rozdělení sezóny na skupiny s vlastní tabulkou.',
						'{ui:seasonManagement.more.resultsEmail} – vyberete odehrané zápasy a pošlete výsledky a tabulku všem v sezóně; nejdřív si můžete poslat test sobě.',
						'{ui:seasonManagement.visibility.label} a {ui:seasonManagement.more.publicPage}.',
					] },
				],
			},
			en: {
				title: 'Managing a season',
				summary: 'Where season management lives and what to check regularly.',
				keywords: ['season', 'overview', 'tabs', 'attention', 'visibility', 'scoring'],
				blocks: [
					{ type: 'h', id: 'kde', text: 'Where to find it' },
					{ type: 'p', text: 'In the account menu choose {ui:nav.mySeasons} and open a season. It has the tabs {ui:seasonManagement.tabs.season}, {ui:seasonManagement.tabs.games}, {ui:seasonManagement.tabs.teams}, {ui:seasonManagement.tabs.table} and {ui:seasonManagement.tabs.more}.' },
					{ type: 'h', id: 'zalozka-sezona', text: 'The Season tab' },
					{ type: 'list', items: [
						'the season status with {ui:seasonManagement.publish.action} or {ui:seasonManagement.publish.complete};',
						'counts of teams, games and played games;',
						'{ui:seasonManagement.attention.label} – no teams, no schedule, or games without a date;',
						'{ui:seasonManagement.nextUp.label}.',
					] },
					{ type: 'h', id: 'kontrola', text: 'What to check regularly' },
					{ type: 'steps', items: [
						'Does every game have a date? Teams do not see undated games in their schedule.',
						'Are played games waiting for confirmation? The table marks them {ui:seasonManagement.table.awaitingConfirmation} and does not count them yet.',
						'Is the season visible to the right people?',
					] },
					{ type: 'h', id: 'vice', text: 'The More tab' },
					{ type: 'list', items: [
						'{ui:seasonManagement.more.generateSchedule}',
						'{ui:seasonManagement.more.scoring} – points for a win and a draw; the sport default applies until you change it.',
						'{ui:seasonManagement.more.divisions} – split the season into divisions, each with its own table.',
						'{ui:seasonManagement.more.resultsEmail} – pick finished games and email the results and table to everyone in the season; send yourself a test first if you like.',
						'{ui:seasonManagement.visibility.label} and {ui:seasonManagement.more.publicPage}.',
					] },
				],
			},
		},
	},
	{
		slug: 'sezony-a-tymy',
		category: 'league',
		audiences: ['LEAGUE'],
		order: 2,
		updatedAt: '2026-09-14',
		published: true,
		related: ['sprava-sezony', 'rozpis-zapasu', 'profil-tymu-a-soupiska'],
		content: {
			cs: {
				title: 'Sezóny a týmy',
				summary: 'Založení sezóny, její stav a viditelnost a přiřazení týmů.',
				keywords: ['nová sezóna', 'stav', 'koncept', 'aktivní', 'dokončená', 'viditelnost', 'archivace', 'přidat tým', 'odebrat tým'],
				blocks: [
					{ type: 'h', id: 'zalozeni', text: 'Založení sezóny' },
					{ type: 'steps', items: [
						'V menu účtu zvolte {ui:nav.mySeasons} a potom {ui:seasonManagement.newSeason}.',
						'Vyplňte ligu, název a datum začátku a konce. Sezónu lze založit jen v lize, kterou spravujete.',
						'Při zakládání můžete převzít týmy z předchozí sezóny.',
					] },
					{ type: 'h', id: 'stavy', text: 'Stavy sezóny' },
					{ type: 'defs', items: [
						['{ui:seasonManagement.status.DRAFT}', 'Sezóna se připravuje. Jen v tomto stavu lze vygenerovat rozpis.'],
						['{ui:seasonManagement.status.ACTIVE}', 'Hrají se zápasy. Z konceptu ji převede {ui:seasonManagement.publish.action}.'],
						['{ui:seasonManagement.status.COMPLETED}', 'Výsledky jsou konečné. Z aktivní sezóny ji převede {ui:seasonManagement.publish.complete}.'],
					] },
					{ type: 'p', text: 'Stav neurčuje, kdo sezónu uvidí. To řídí viditelnost.' },
					{ type: 'h', id: 'viditelnost', text: 'Viditelnost' },
					{ type: 'defs', items: [
						['{ui:seasonManagement.visibility.PUBLIC.title}', 'Sezónu najde kdokoli.'],
						['{ui:seasonManagement.visibility.UNLISTED.title}', 'Otevře ji každý, komu pošlete odkaz, ale v seznamech ani ve vyhledávání není. Nová sezóna začíná takto.'],
						['{ui:seasonManagement.visibility.PRIVATE.title}', 'Sezónu vidí jen ti, kdo ligu spravují.'],
					] },
					{ type: 'p', text: 'Neveřejná nebo skrytá liga platí i pro všechny své sezóny, ať jsou nastavené jakkoli.' },
					{ type: 'h', id: 'archivace', text: 'Archivace' },
					{ type: 'p', text: 'Sezónu archivuje administrátor. Archivovat lze jen dokončenou sezónu, ve které jsou všechny odehrané zápasy potvrzené. Zůstane jen konečná tabulka a celkové statistiky hráčů a sezónu už nelze měnit.' },
					{ type: 'h', id: 'tymy', text: 'Přidání týmů' },
					{ type: 'steps', items: [
						'Otevřete sezónu a záložku {ui:seasonManagement.tabs.teams}.',
						'Zvolte {ui:seasonManagement.teams.add}.',
						'U rozdělené sezóny zařaďte tým do skupiny v {ui:seasonManagement.tabs.more} → {ui:seasonManagement.more.divisions}.',
						'Pozvěte manažera týmu tlačítkem {ui:teamDetail.inviteManager.button}.',
					] },
					{ type: 'h', id: 'odebrani', text: 'Odebrání týmu ze sezóny' },
					{ type: 'note', tone: 'important', text: 'Odebráním týmu ze sezóny se smažou všechny jeho zápasy v této sezóně včetně zapsaných výsledků a statistik. Tým a jeho soupiska zůstanou zachované.' },
				],
			},
			en: {
				title: 'Seasons and teams',
				summary: 'Creating a season, its status and visibility, and adding teams.',
				keywords: ['new season', 'status', 'draft', 'active', 'completed', 'visibility', 'archive', 'add team', 'remove team'],
				blocks: [
					{ type: 'h', id: 'zalozeni', text: 'Creating a season' },
					{ type: 'steps', items: [
						'In the account menu choose {ui:nav.mySeasons}, then {ui:seasonManagement.newSeason}.',
						'Fill in the league, name, start and end date. You can only create a season in a league you manage.',
						'You can carry teams over from the previous season while creating it.',
					] },
					{ type: 'h', id: 'stavy', text: 'Season status' },
					{ type: 'defs', items: [
						['{ui:seasonManagement.status.DRAFT}', 'Being prepared. The schedule can only be generated in this status.'],
						['{ui:seasonManagement.status.ACTIVE}', 'Games are being played. {ui:seasonManagement.publish.action} moves a draft here.'],
						['{ui:seasonManagement.status.COMPLETED}', 'Results are final. {ui:seasonManagement.publish.complete} moves an active season here.'],
					] },
					{ type: 'p', text: 'Status does not decide who can see a season. Visibility does.' },
					{ type: 'h', id: 'viditelnost', text: 'Visibility' },
					{ type: 'defs', items: [
						['{ui:seasonManagement.visibility.PUBLIC.title}', 'Anyone can find the season.'],
						['{ui:seasonManagement.visibility.UNLISTED.title}', 'Anyone with the link can open it, but it is not in lists or search. New seasons start here.'],
						['{ui:seasonManagement.visibility.PRIVATE.title}', 'Only the people who manage the league can see it.'],
					] },
					{ type: 'p', text: 'An unpublished or hidden league applies to all its seasons, whatever they are set to.' },
					{ type: 'h', id: 'archivace', text: 'Archiving' },
					{ type: 'p', text: 'An administrator archives seasons. Only a completed season whose played games are all confirmed can be archived. Only the final table and player totals remain, and the season can no longer change.' },
					{ type: 'h', id: 'tymy', text: 'Adding teams' },
					{ type: 'steps', items: [
						'Open the season and the {ui:seasonManagement.tabs.teams} tab.',
						'Choose {ui:seasonManagement.teams.add}.',
						'In a divided season, place the team in a division under {ui:seasonManagement.tabs.more} → {ui:seasonManagement.more.divisions}.',
						'Invite the team manager with {ui:teamDetail.inviteManager.button}.',
					] },
					{ type: 'h', id: 'odebrani', text: 'Removing a team from a season' },
					{ type: 'note', tone: 'important', text: 'Removing a team from a season deletes all its games in that season, including recorded results and statistics. The team and its roster are kept.' },
				],
			},
		},
	},
	{
		slug: 'rozpis-zapasu',
		category: 'league',
		audiences: ['LEAGUE'],
		order: 3,
		updatedAt: '2026-09-14',
		published: true,
		related: ['sezony-a-tymy', 'vysledky-a-statistiky', 'sprava-sezony'],
		content: {
			cs: {
				title: 'Rozpis zápasů',
				summary: 'Vygenerování rozpisu a nastavení termínů.',
				keywords: ['rozpis', 'generovat', 'kolo', 'termín', 'datum', 'skupiny'],
				blocks: [
					{ type: 'h', id: 'predtim', text: 'Než začnete' },
					{ type: 'list', items: [
						'Sezóna musí být ve stavu {ui:seasonManagement.status.DRAFT}.',
						'V sezóně musí být alespoň dva týmy.',
						'U rozdělené sezóny zařaďte týmy do skupin předem.',
					] },
					{ type: 'h', id: 'generovani', text: 'Vygenerování rozpisu' },
					{ type: 'steps', items: [
						'Otevřete sezónu a záložku {ui:seasonManagement.tabs.more}.',
						'Zvolte {ui:seasonManagement.more.generateSchedule}.',
						'Zadejte počet kol. Každé kolo je jedno kompletní „každý s každým“; v sudých kolech se prohodí domácí a hosté.',
						'U rozdělené sezóny zvolte, zda se hraje jen v rámci skupin.',
					] },
					{ type: 'p', text: 'ATM seřadí zápasy tak, aby tým pokud možno nehrál dva zápasy po sobě. Vygenerované zápasy nemají termín.' },
					{ type: 'note', tone: 'important', text: 'Opakované vygenerování smaže všechny zápasy sezóny včetně nastavených termínů a případných výsledků a vytvoří je znovu.' },
					{ type: 'h', id: 'terminy', text: 'Nastavení termínů' },
					{ type: 'list', items: [
						'Na záložce {ui:seasonManagement.tabs.season} zvolte {ui:seasonManagement.attention.setDates} a zadejte termín pro celé kolo.',
						'Jednotlivý zápas upravíte na záložce {ui:seasonManagement.tabs.games} přes {ui:seasonManagement.games.setDate} nebo {ui:seasonManagement.games.edit}.',
					] },
					{ type: 'p', text: 'Zápas s termínem se oběma týmům objeví v rozpisu i v kalendáři.' },
				],
			},
			en: {
				title: 'Game schedule',
				summary: 'Generating the schedule and setting dates.',
				keywords: ['schedule', 'generate', 'round', 'date', 'fixtures', 'divisions'],
				blocks: [
					{ type: 'h', id: 'predtim', text: 'Before you start' },
					{ type: 'list', items: [
						'The season must be in {ui:seasonManagement.status.DRAFT}.',
						'The season needs at least two teams.',
						'In a divided season, place teams in divisions first.',
					] },
					{ type: 'h', id: 'generovani', text: 'Generating the schedule' },
					{ type: 'steps', items: [
						'Open the season and the {ui:seasonManagement.tabs.more} tab.',
						'Choose {ui:seasonManagement.more.generateSchedule}.',
						'Enter the number of rounds. Each round is one full round robin; home and away swap in even rounds.',
						'In a divided season, choose whether teams play only within their division.',
					] },
					{ type: 'p', text: 'ATM orders games so a team avoids playing twice in a row where possible. Generated games have no date.' },
					{ type: 'note', tone: 'important', text: 'Generating again deletes every game in the season, including dates and any results, and creates them anew.' },
					{ type: 'h', id: 'terminy', text: 'Setting dates' },
					{ type: 'list', items: [
						'On the {ui:seasonManagement.tabs.season} tab choose {ui:seasonManagement.attention.setDates} and set a date for a whole round.',
						'Change a single game on the {ui:seasonManagement.tabs.games} tab with {ui:seasonManagement.games.setDate} or {ui:seasonManagement.games.edit}.',
					] },
					{ type: 'p', text: 'Once a game has a date, it appears in both teams’ schedules and calendars.' },
				],
			},
		},
	},
	{
		slug: 'vysledky-a-statistiky',
		category: 'league',
		audiences: ['LEAGUE', 'TEAM'],
		order: 4,
		updatedAt: '2026-09-14',
		published: true,
		related: ['rozpis-zapasu', 'sprava-sezony', 'nejcastejsi-otazky'],
		content: {
			cs: {
				title: 'Výsledky a statistiky',
				summary: 'Zápis výsledku, zápis o utkání, potvrzení a výpočet tabulky.',
				keywords: ['výsledek', 'skóre', 'zápis o utkání', 'gól', 'trest', 'potvrdit', 'tabulka', 'statistiky'],
				blocks: [
					{ type: 'h', id: 'vysledek', text: 'Zápis výsledku' },
					{ type: 'steps', items: [
						'Na záložce {ui:seasonManagement.tabs.games} zvolte u zápasu {ui:seasonManagement.games.result}.',
						'V okně {ui:seasonManagement.result.title} vyplňte skóre a zvolte {ui:seasonManagement.result.save}.',
						'Pokud se zápas neodehrál, změňte jeho stav a zvolte {ui:seasonManagement.result.saveStatus}.',
					] },
					{ type: 'h', id: 'zapis', text: 'Zápis o utkání' },
					{ type: 'p', text: 'V {ui:seasonManagement.report.title} zapisujete průběh zápasu: {ui:seasonManagement.report.addGoal} se střelcem a asistencemi a {ui:seasonManagement.report.addPenalty} s trestnými minutami. Jakmile má zápas zápis o utkání, skóre i statistiky hráčů se počítají z něj a ručně je přepsat nelze.' },
					{ type: 'h', id: 'potvrzeni', text: 'Potvrzení' },
					{ type: 'p', text: 'Do tabulky se počítá jen potvrzený zápas. Odehraný zápas potvrdíte v zápisu o utkání tlačítkem {ui:seasonManagement.report.confirm}.' },
					{ type: 'p', text: 'Potvrzený zápas nelze měnit. Pro opravu zvolte {ui:seasonManagement.report.reopen} a uveďte důvod; potvrzení i znovuotevření se zaznamenají do historie zápisu.' },
					{ type: 'h', id: 'manazer-tymu', text: 'Statistiky od manažera týmu' },
					{ type: 'p', text: 'Manažer týmu může u zápasu svého týmu vyplnit {ui:teamManagement.gameStats.goals}, {ui:teamManagement.gameStats.assists} a {ui:teamManagement.gameStats.penaltyMinutesShort} svých hráčů – jen dokud zápas není potvrzený a nemá zápis o utkání.' },
					{ type: 'h', id: 'tabulka', text: 'Jak vzniká tabulka' },
					{ type: 'p', text: 'Tabulka se počítá z potvrzených výsledků a z nastavení {ui:seasonManagement.more.scoring}. Ručně se neupravuje. Statistiky hráčů opravujte v původním zápase, ne u hráče.' },
				],
			},
			en: {
				title: 'Results and statistics',
				summary: 'Recording results, match reports, confirmation and how the table is built.',
				keywords: ['result', 'score', 'match report', 'goal', 'penalty', 'confirm', 'table', 'statistics'],
				blocks: [
					{ type: 'h', id: 'vysledek', text: 'Recording a result' },
					{ type: 'steps', items: [
						'On the {ui:seasonManagement.tabs.games} tab choose {ui:seasonManagement.games.result} on the game.',
						'In {ui:seasonManagement.result.title} enter the score and choose {ui:seasonManagement.result.save}.',
						'If the game was not played, change its status and choose {ui:seasonManagement.result.saveStatus}.',
					] },
					{ type: 'h', id: 'zapis', text: 'Match report' },
					{ type: 'p', text: 'The {ui:seasonManagement.report.title} records what happened: a {ui:seasonManagement.report.addGoal} with scorer and assists, a {ui:seasonManagement.report.addPenalty} with penalty minutes. Once a game has a match report, its score and player statistics come from it and cannot be overwritten by hand.' },
					{ type: 'h', id: 'potvrzeni', text: 'Confirmation' },
					{ type: 'p', text: 'Only confirmed games count in the table. Confirm a played game in its match report with {ui:seasonManagement.report.confirm}.' },
					{ type: 'p', text: 'A confirmed game cannot change. To correct it, choose {ui:seasonManagement.report.reopen} and give a reason; confirmations and reopenings are kept in the report history.' },
					{ type: 'h', id: 'manazer-tymu', text: 'Statistics from the team manager' },
					{ type: 'p', text: 'A team manager can fill in {ui:teamManagement.gameStats.goals}, {ui:teamManagement.gameStats.assists} and {ui:teamManagement.gameStats.penaltyMinutesShort} for their own players – only while the game is unconfirmed and has no match report.' },
					{ type: 'h', id: 'tabulka', text: 'How the table is built' },
					{ type: 'p', text: 'The table comes from confirmed results and the {ui:seasonManagement.more.scoring}. It is never edited by hand. Correct player statistics in the game they came from, not on the player.' },
				],
			},
		},
	},

	// ------------------------------------------------------------------- team
	{
		slug: 'sprava-tymu',
		category: 'team',
		audiences: ['TEAM'],
		order: 1,
		updatedAt: '2026-09-14',
		published: true,
		related: ['profil-tymu-a-soupiska', 'kalendar-a-udalosti', 'role-a-opravneni'],
		content: {
			cs: {
				title: 'Správa týmu',
				summary: 'Kde správu týmu najdete a co v ní děláte.',
				keywords: ['tým', 'přehled', 'soupiska', 'rozpis', 'kalendář', 'nastavení'],
				blocks: [
					{ type: 'h', id: 'kde', text: 'Kde správu najdete' },
					{ type: 'p', text: 'V menu účtu zvolte {ui:nav.myTeams} a otevřete tým. Správa má záložky {ui:teamManagement.pwa.tabs.overview}, {ui:teamManagement.pwa.tabs.roster}, {ui:teamManagement.pwa.tabs.schedule}, {ui:teamManagement.pwa.tabs.events} a {ui:teamManagement.pwa.tabs.settings}. Při první návštěvě vás provede krátká prohlídka.' },
					{ type: 'h', id: 'postup', text: 'Doporučený postup' },
					{ type: 'steps', items: [
						'Na záložce {ui:teamManagement.pwa.tabs.overview} zkontrolujte nejbližší zápas.',
						'Na záložce {ui:teamManagement.pwa.tabs.roster} udržujte aktuální hráče.',
						'V {ui:teamManagement.pwa.tabs.events} naplánujte tréninky a sledujte docházku.',
						'Po zápase vyplňte statistiky svých hráčů, pokud manažer ligy nevede zápis o utkání.',
					] },
					{ type: 'note', tone: 'tip', text: 'Termíny, skóre, rozpis a potvrzování zápisů patří manažerovi ligy. Když potřebujete změnu, obraťte se na něj.' },
				],
			},
			en: {
				title: 'Managing a team',
				summary: 'Where team management lives and what you do there.',
				keywords: ['team', 'overview', 'roster', 'schedule', 'calendar', 'settings'],
				blocks: [
					{ type: 'h', id: 'kde', text: 'Where to find it' },
					{ type: 'p', text: 'In the account menu choose {ui:nav.myTeams} and open a team. It has the tabs {ui:teamManagement.pwa.tabs.overview}, {ui:teamManagement.pwa.tabs.roster}, {ui:teamManagement.pwa.tabs.schedule}, {ui:teamManagement.pwa.tabs.events} and {ui:teamManagement.pwa.tabs.settings}. A short tour guides you on your first visit.' },
					{ type: 'h', id: 'postup', text: 'A good routine' },
					{ type: 'steps', items: [
						'On {ui:teamManagement.pwa.tabs.overview}, check the next game.',
						'On {ui:teamManagement.pwa.tabs.roster}, keep players up to date.',
						'In {ui:teamManagement.pwa.tabs.events}, plan training and follow attendance.',
						'After a game, fill in your players’ statistics unless the league manager keeps a match report.',
					] },
					{ type: 'note', tone: 'tip', text: 'Dates, scores, the schedule and confirming reports belong to the league manager. Ask them when something needs to change.' },
				],
			},
		},
	},
	{
		slug: 'profil-tymu-a-soupiska',
		category: 'team',
		audiences: ['TEAM'],
		order: 2,
		updatedAt: '2026-09-14',
		published: true,
		related: ['nastaveni-tymu', 'sprava-tymu', 'vysledky-a-statistiky'],
		content: {
			cs: {
				title: 'Profil týmu a soupiska',
				summary: 'Hráči, čísla dresů a propojení hráčů s účty.',
				keywords: ['soupiska', 'hráč', 'přidat hráče', 'číslo dresu', 'pozice', 'duplicita', 'účet hráče'],
				blocks: [
					{ type: 'h', id: 'pridani', text: 'Přidání hráče' },
					{ type: 'steps', items: [
						'Otevřete záložku {ui:teamManagement.pwa.tabs.roster}.',
						'Přes {ui:teamManagement.pwa.searchPlayers} ověřte, že hráč v soupisce ještě není.',
						'Zvolte {ui:teamManagement.pwa.addPlayer}.',
						'Vyplňte jméno a podle potřeby číslo dresu, pozici, rok narození a poznámku.',
					] },
					{ type: 'p', text: 'Hráč patří k týmu, ne k sezóně. Když tým hraje další sezónu, soupiska zůstává.' },
					{ type: 'h', id: 'ucet', text: 'Propojení hráče s účtem' },
					{ type: 'p', text: 'V detailu hráče ho můžete propojit s existujícím uživatelským účtem. Hráč pak po přihlášení vidí svůj tým a sám odpovídá na docházku. Propojení lze zrušit; hráč i jeho statistiky zůstanou.' },
					{ type: 'h', id: 'duplicity', text: 'Duplicitní hráči' },
					{ type: 'note', tone: 'important', text: 'Nezakládejte nového hráče kvůli změně čísla nebo pozice – upravte stávajícího. Duplicitní záznam rozdělí statistiky jednoho člověka do dvou a ATM je sloučit neumí.' },
				],
			},
			en: {
				title: 'Team profile and roster',
				summary: 'Players, shirt numbers and linking players to accounts.',
				keywords: ['roster', 'player', 'add player', 'shirt number', 'position', 'duplicate', 'player account'],
				blocks: [
					{ type: 'h', id: 'pridani', text: 'Adding a player' },
					{ type: 'steps', items: [
						'Open the {ui:teamManagement.pwa.tabs.roster} tab.',
						'Use {ui:teamManagement.pwa.searchPlayers} to make sure the player is not already there.',
						'Choose {ui:teamManagement.pwa.addPlayer}.',
						'Enter the name and, as needed, shirt number, position, year of birth and a note.',
					] },
					{ type: 'p', text: 'A player belongs to the team, not to a season. When the team plays another season, the roster stays.' },
					{ type: 'h', id: 'ucet', text: 'Linking a player to an account' },
					{ type: 'p', text: 'In the player detail you can link them to an existing user account. The player then sees their team after signing in and answers attendance themselves. The link can be removed; the player and their statistics stay.' },
					{ type: 'h', id: 'duplicity', text: 'Duplicate players' },
					{ type: 'note', tone: 'important', text: 'Do not create a new player because a number or position changed – edit the existing one. A duplicate splits one person’s statistics in two, and ATM cannot merge them.' },
				],
			},
		},
	},
	{
		slug: 'kalendar-a-udalosti',
		category: 'team',
		audiences: ['TEAM'],
		order: 3,
		updatedAt: '2026-09-14',
		published: true,
		related: ['sprava-tymu', 'rozpis-zapasu'],
		content: {
			cs: {
				title: 'Kalendář a události',
				summary: 'Tréninky, schůzky a docházka hráčů.',
				keywords: ['kalendář', 'událost', 'trénink', 'schůzka', 'docházka', 'přijdu'],
				blocks: [
					{ type: 'h', id: 'zapasy', text: 'Zápasy v kalendáři' },
					{ type: 'p', text: 'Zápas s termínem se v {ui:teamManagement.pwa.tabs.events} objeví sám. Zápasy ze soutěže se ručně nezakládají.' },
					{ type: 'h', id: 'udalost', text: 'Přidání události' },
					{ type: 'steps', items: [
						'Otevřete záložku {ui:teamManagement.pwa.tabs.events} a přidejte událost.',
						'Zvolte typ: {ui:teamManagement.events.type.TRAINING}, {ui:teamManagement.events.type.MEETING} nebo {ui:teamManagement.events.type.OTHER}.',
						'Vyplňte název, začátek a případně místo.',
					] },
					{ type: 'h', id: 'dochazka', text: 'Docházka' },
					{ type: 'p', text: 'U každé události hráči odpovídají {ui:teamManagement.events.status.ATTENDING}, {ui:teamManagement.events.status.NOT_ATTENDING} nebo {ui:teamManagement.events.status.MAYBE}. Hráč s propojeným účtem odpovídá sám, za ostatní odpovídá manažer.' },
				],
			},
			en: {
				title: 'Calendar and events',
				summary: 'Training, meetings and player attendance.',
				keywords: ['calendar', 'event', 'training', 'meeting', 'attendance', 'attending'],
				blocks: [
					{ type: 'h', id: 'zapasy', text: 'Games in the calendar' },
					{ type: 'p', text: 'A game with a date appears in the {ui:teamManagement.pwa.tabs.events} on its own. Competition games are never added by hand.' },
					{ type: 'h', id: 'udalost', text: 'Adding an event' },
					{ type: 'steps', items: [
						'Open the {ui:teamManagement.pwa.tabs.events} tab and add an event.',
						'Pick a type: {ui:teamManagement.events.type.TRAINING}, {ui:teamManagement.events.type.MEETING} or {ui:teamManagement.events.type.OTHER}.',
						'Fill in the title, start and, if you like, the place.',
					] },
					{ type: 'h', id: 'dochazka', text: 'Attendance' },
					{ type: 'p', text: 'For each event players answer {ui:teamManagement.events.status.ATTENDING}, {ui:teamManagement.events.status.NOT_ATTENDING} or {ui:teamManagement.events.status.MAYBE}. A player linked to an account answers for themselves; the manager answers for everyone else.' },
				],
			},
		},
	},
	{
		slug: 'nastaveni-tymu',
		category: 'team',
		audiences: ['TEAM'],
		order: 4,
		updatedAt: '2026-09-14',
		published: true,
		related: ['profil-tymu-a-soupiska', 'role-a-opravneni'],
		content: {
			cs: {
				title: 'Nastavení týmu',
				summary: 'Název, logo a barva týmu a kdo zve manažery.',
				keywords: ['nastavení', 'název týmu', 'logo', 'barva', 'pozvat manažera'],
				blocks: [
					{ type: 'h', id: 'udaje', text: 'Údaje týmu' },
					{ type: 'p', text: 'Na záložce {ui:teamManagement.pwa.tabs.settings} upravíte {ui:teamManagement.pwa.teamName}. V části {ui:teamManagement.branding.title} nastavíte logo a barvu. Tyto údaje se ukazují v rozpisu, tabulce i na veřejném profilu týmu.' },
					{ type: 'h', id: 'manazeri', text: 'Manažeři týmu' },
					{ type: 'p', text: 'Nového manažera týmu zve manažer ligy, ve které tým hraje, nebo administrátor. Manažer týmu sám další manažery nezve a tým nemaže.' },
				],
			},
			en: {
				title: 'Team settings',
				summary: 'The team name, logo and colour, and who invites managers.',
				keywords: ['settings', 'team name', 'logo', 'colour', 'invite manager'],
				blocks: [
					{ type: 'h', id: 'udaje', text: 'Team details' },
					{ type: 'p', text: 'On the {ui:teamManagement.pwa.tabs.settings} tab you edit the {ui:teamManagement.pwa.teamName}. {ui:teamManagement.branding.title} sets the logo and colour. They appear in the schedule, the table and the public team profile.' },
					{ type: 'h', id: 'manazeri', text: 'Team managers' },
					{ type: 'p', text: 'A new team manager is invited by the manager of a league the team plays in, or by an administrator. A team manager does not invite other managers or delete the team.' },
				],
			},
		},
	},

	// ------------------------------------------------------------------- more
	{
		slug: 'turnaje-skupiny-a-playoff',
		category: 'more',
		audiences: ['TOURNAMENT'],
		order: 1,
		updatedAt: '2026-09-14',
		published: true,
		related: ['role-a-opravneni', 'vysledky-a-statistiky'],
		content: {
			cs: {
				title: 'Turnaje, skupiny a playoff',
				summary: 'Série turnajů, skupinová fáze a vyřazovací pavouk.',
				keywords: ['turnaj', 'série', 'skupiny', 'playoff', 'pavouk', 'tenis'],
				blocks: [
					{ type: 'h', id: 'serie', text: 'Série a turnaje' },
					{ type: 'p', text: 'Pokud spravujete sérii turnajů, najdete v menu účtu {ui:nav.manageTournaments}. {ui:tm.series.title} sdružují jednotlivé ročníky a nesou sport a viditelnost pro všechny své turnaje. Týmy a hráči turnaje jsou samostatné a nesouvisí s ligami.' },
					{ type: 'h', id: 'stavy', text: 'Stavy turnaje' },
					{ type: 'p', text: '{ui:tm.tournamentStatus.DRAFT}, {ui:tm.tournamentStatus.REGISTRATION}, {ui:tm.tournamentStatus.GROUP_STAGE}, {ui:tm.tournamentStatus.PLAYOFF}, {ui:tm.tournamentStatus.COMPLETED}.' },
					{ type: 'h', id: 'postup', text: 'Postup' },
					{ type: 'steps', items: [
						'Na záložce {ui:tm.tournament.tabs.teams} (u tenisu {ui:tm.tournament.tabs.teams_TENNIS}) přidejte účastníky.',
						'Na záložce {ui:tm.tournament.tabs.groups} vytvořte skupiny, rozdělte do nich účastníky a vygenerujte rozpis skupinové fáze.',
						'Výsledky zapisujte na záložce {ui:tm.tournament.tabs.results}.',
						'Po skupinové fázi zvolte na záložce {ui:tm.tournament.tabs.playoff} {ui:tm.tournament.playoff.generatePlayoffs}.',
					] },
					{ type: 'note', tone: 'important', text: 'Smazání rozpisu skupinové fáze nebo playoff pavouka nelze vrátit. Pořadí ve skupinách zkontrolujte dřív, než pavouk vygenerujete.' },
				],
			},
			en: {
				title: 'Tournaments, groups and playoff',
				summary: 'Tournament series, the group stage and the knockout bracket.',
				keywords: ['tournament', 'series', 'groups', 'playoff', 'bracket', 'tennis'],
				blocks: [
					{ type: 'h', id: 'serie', text: 'Series and tournaments' },
					{ type: 'p', text: 'If you manage a tournament series, the account menu has {ui:nav.manageTournaments}. {ui:tm.series.title} group the editions and carry the sport and visibility for all their tournaments. Tournament teams and players are separate from leagues.' },
					{ type: 'h', id: 'stavy', text: 'Tournament status' },
					{ type: 'p', text: '{ui:tm.tournamentStatus.DRAFT}, {ui:tm.tournamentStatus.REGISTRATION}, {ui:tm.tournamentStatus.GROUP_STAGE}, {ui:tm.tournamentStatus.PLAYOFF}, {ui:tm.tournamentStatus.COMPLETED}.' },
					{ type: 'h', id: 'postup', text: 'Step by step' },
					{ type: 'steps', items: [
						'On the {ui:tm.tournament.tabs.teams} tab ({ui:tm.tournament.tabs.teams_TENNIS} for tennis) add the entrants.',
						'On the {ui:tm.tournament.tabs.groups} tab create groups, place entrants and generate the group-stage schedule.',
						'Record results on the {ui:tm.tournament.tabs.results} tab.',
						'After the group stage, choose {ui:tm.tournament.playoff.generatePlayoffs} on the {ui:tm.tournament.tabs.playoff} tab.',
					] },
					{ type: 'note', tone: 'important', text: 'Deleting the group-stage schedule or the playoff bracket cannot be undone. Check the group standings before generating the bracket.' },
				],
			},
		},
	},
	{
		slug: 'nejcastejsi-otazky',
		category: 'more',
		audiences: ['ALL'],
		order: 2,
		updatedAt: '2026-09-14',
		published: true,
		related: ['vysledky-a-statistiky', 'role-a-opravneni', 'rozpis-zapasu'],
		content: {
			cs: {
				title: 'Nejčastější otázky',
				summary: 'Rychlé odpovědi na běžné potíže.',
				keywords: ['otázky', 'faq', 'problém', 'nevidím', 'tabulka', 'termín'],
				blocks: [
					{ type: 'h', id: 'nevidim-tym', text: 'Proč nevidím svůj tým nebo ligu?' },
					{ type: 'p', text: 'Pravděpodobně jste přihlášeni jiným e-mailem, než na který přišla pozvánka. Pokud tým stále chybí, požádejte manažera ligy o novou pozvánku.' },
					{ type: 'h', id: 'tabulka', text: 'Proč se výsledek neprojevil v tabulce?' },
					{ type: 'p', text: 'Do tabulky se počítají jen potvrzené zápasy. Zápas označený {ui:seasonManagement.table.awaitingConfirmation} musí manažer ligy potvrdit.' },
					{ type: 'h', id: 'statistiky', text: 'Proč nemohu změnit statistiky zápasu?' },
					{ type: 'p', text: 'Zápas je buď potvrzený – pak ho musí manažer ligy znovu otevřít – nebo má zápis o utkání a statistiky se počítají z něj.' },
					{ type: 'h', id: 'rozpis-tymu', text: 'Proč tým nevidí zápas v rozpisu?' },
					{ type: 'p', text: 'Zápas nemá termín. Manažer ligy ho nastaví na záložce {ui:seasonManagement.tabs.games} nebo přes {ui:seasonManagement.attention.setDates}.' },
					{ type: 'h', id: 'generovani', text: 'Proč nejde vygenerovat rozpis?' },
					{ type: 'p', text: 'Rozpis lze vygenerovat jen v sezóně ve stavu {ui:seasonManagement.status.DRAFT} s alespoň dvěma týmy.' },
					{ type: 'h', id: 'vice-tymu', text: 'Mohu spravovat více týmů nebo lig?' },
					{ type: 'p', text: 'Ano. Stačí být uveden jako manažer každého z nich; všechny oblasti pak máte v menu účtu.' },
				],
			},
			en: {
				title: 'Frequently asked questions',
				summary: 'Quick answers to common problems.',
				keywords: ['questions', 'faq', 'problem', 'missing', 'table', 'date'],
				blocks: [
					{ type: 'h', id: 'nevidim-tym', text: 'Why can’t I see my team or league?' },
					{ type: 'p', text: 'You are most likely signed in with a different email from the one the invitation went to. If the team is still missing, ask the league manager for a new invitation.' },
					{ type: 'h', id: 'tabulka', text: 'Why isn’t a result in the table?' },
					{ type: 'p', text: 'Only confirmed games count. A game marked {ui:seasonManagement.table.awaitingConfirmation} has to be confirmed by the league manager.' },
					{ type: 'h', id: 'statistiky', text: 'Why can’t I change a game’s statistics?' },
					{ type: 'p', text: 'Either the game is confirmed – the league manager has to reopen it – or it has a match report and the statistics come from it.' },
					{ type: 'h', id: 'rozpis-tymu', text: 'Why doesn’t a team see a game in its schedule?' },
					{ type: 'p', text: 'The game has no date. The league manager sets it on the {ui:seasonManagement.tabs.games} tab or with {ui:seasonManagement.attention.setDates}.' },
					{ type: 'h', id: 'generovani', text: 'Why can’t I generate the schedule?' },
					{ type: 'p', text: 'The schedule can only be generated in a season in {ui:seasonManagement.status.DRAFT} with at least two teams.' },
					{ type: 'h', id: 'vice-tymu', text: 'Can I manage several teams or leagues?' },
					{ type: 'p', text: 'Yes. You need to be named manager of each; all of them then appear in your account menu.' },
				],
			},
		},
	},
];
